url: https://data.services.jetbrains.com/products
software:
-   product_name: IDEA
    product_code: IIU
    parameters: ?code=IIU&release.type=eap%2Crc%2Crelease&fields=distributions%2Clink%2Cname%2Creleases&_={timestamp}

-   product_name: Goland
    product_code: Go
    parameters: ?code=GO&release.type=eap%2Crc%2Crelease&fields=distributions%2Clink%2Cname%2Creleases&_={timestamp}

-   product_name: WebStorm
    product_code: WS
    parameters: ?code=WS&release.type=eap%2Crc%2Crelease&fields=distributions%2Clink%2Cname%2Creleases&_={timestamp}

-   product_name: PhpStorm
    product_code: PS
    parameters: ?code=PS&release.type=eap%2Crc%2Crelease&fields=distributions%2Clink%2Cname%2Creleases&_={timestamp}

-   product_name: PyCharm
    product_code: PCP
    parameters: ?code=PC&release.type=eap%2Crc%2Crelease&fields=distributions%2Clink%2Cname%2Creleases&_={timestamp}